# Generated by Django 2.2 on 2021-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200616_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='accepted_terms',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
