name: Test and Publish
on:
  pull_request:
    branches:
      - develop
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry and build package
        uses: dschep/install-poetry-action@v1.3
        run: poetry build

      - name: Test
        run: poetry run pytest src
