---
name: Deploy To dev.giantmade.net

on: 
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: giantmade/github-actions/.github/workflows/deploy-dev.yml@main
    with: 
      branch: ${{ github.head_ref }}