---
name: Lint & Autolint

on:
  pull_request:
    branches: 
     - main
     - develop

jobs:
  lint-and-autolint:
    name: Isort, Flake8 & Black
    uses: giantmade/github-actions/.github/workflows/lint.yml@main
    secrets: inherit
    with:
      python-version: "3.9.x"
